/* Generated by Microsoft Visual Code C/C++ Extension */

#pragma once

/* Place your custom directives and preprocessors below this comment */

#if defined(__linux__) || defined(__APPLE__)
    #define CLEAR system("clear")
    #define PAUSE system("read")
#else
    #define CLEAR system("cls")
    #define PAUSE system("pause")
#endif

// Boolean compatibility
typedef enum {false, true} bool;